'use client'

import Link from 'next/link'
import { Bell, CheckCircle2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/components/client-shell'
import { Layout } from '@/components/client-layout'
import { card, button } from '@/components/client-shell'

type Notification = { id: string; title: string; message: string; is_read: boolean; created_at: string; project_id: string | null; request_id: string | null }

export function ClientNotificationsPage() { const { profile, loading: authLoading } = useAuth(); const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = async () => { if (!profile) return; const { data, error: queryError } = await createClient().from('notifications').select('id,title,message,is_read,created_at,project_id,request_id').eq('user_id', profile.id).order('created_at', { ascending: false }); if (queryError) setError('Notifications could not be loaded.'); else setItems((data ?? []) as Notification[]); setLoading(false) }; useEffect(() => { if (!authLoading) void load() }, [authLoading, profile]); const markAll = async () => { if (!profile) return; await createClient().from('notifications').update({ is_read: true }).eq('user_id', profile.id).eq('is_read', false); setItems(current => current.map(item => ({ ...item, is_read: true }))) }; const mark = async (item: Notification) => { if (item.is_read) return; await createClient().from('notifications').update({ is_read: true }).eq('id', item.id).eq('user_id', profile?.id); setItems(current => current.map(value => value.id === item.id ? { ...value, is_read: true } : value)) }; return <Layout title="Notifications"><div className="flex items-center justify-between"><p className="text-sm text-[#9F8189]">Updates about your requests and projects.</p><button onClick={() => void markAll()} className="text-sm text-[#D66A84]">Mark all as read</button></div>{error && <p role="alert" className="mt-5 rounded-xl border border-[#D65C6F]/40 bg-[#D65C6F]/10 p-4 text-sm text-[#E99AAA]">{error}</p>}{loading || authLoading ? <div className="mt-6 space-y-3"><div className="h-20 animate-pulse rounded-2xl bg-[#250C14]" /><div className="h-20 animate-pulse rounded-2xl bg-[#250C14]" /></div> : items.length ? <div className="mt-6 space-y-3">{items.map(item => <Link key={item.id} href={item.project_id ? `/projects/${item.project_id}` : '/projects'} onClick={() => void mark(item)} className={`${card} flex gap-4 p-5 ${item.is_read ? 'opacity-70' : 'border-[#A52546]'}`}><div className="mt-1 rounded-full bg-[#3A101C] p-2"><Bell className="size-4 text-[#D66A84]" /></div><div className="flex-1"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{item.title}</h2>{!item.is_read && <span className="size-2 rounded-full bg-[#D66A84]" />}</div><p className="mt-1 text-sm text-[#C7A7B0]">{item.message}</p><time className="mt-3 block text-xs text-[#9F8189]">{new Date(item.created_at).toLocaleString()}</time></div></Link>)}</div> : <div className={`${card} mt-6 p-12 text-center`}><CheckCircle2 className="mx-auto size-8 text-[#72D59A]" /><h2 className="mt-4 text-xl font-semibold">You&apos;re all caught up.</h2><p className="mt-2 text-sm text-[#9F8189]">New project and creator updates will appear here.</p><Link href="/creators" className={`${button} mt-6`}>Find creators</Link></div>}</Layout> }
