'use client'

import { useEffect, useState } from 'react'
import { Send } from 'lucide-react'
import { useSearchParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/components/client-shell'
import { Layout } from '@/components/client-layout'
import { card, button } from '@/components/client-shell'

type Conversation = { id: string; creator_id: string; project_id: string | null; updated_at: string; creatorName: string; avatar: string | null }
type Message = { id: string; sender_id: string; body: string; created_at: string; read_at: string | null }

export function ClientChatPage({ initialCreatorId }: { initialCreatorId?: string }) {
  const { profile, loading: authLoading } = useAuth(); const params = useSearchParams(); const [conversations, setConversations] = useState<Conversation[]>([]); const [messages, setMessages] = useState<Message[]>([]); const [active, setActive] = useState(''); const [text, setText] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { if (authLoading || !profile) return; const load = async () => { const supabase = createClient(); let requestedCreator = params.get('creatorId') ?? params.get('creator') ?? initialCreatorId; const requestedProject = params.get('project'); if (!requestedCreator && requestedProject) { const { data: project } = await supabase.from('projects').select('creator_id').eq('id', requestedProject).eq('client_id', profile.id).maybeSingle(); requestedCreator = (project as { creator_id?: string } | null)?.creator_id ?? undefined } const { data, error: queryError } = await supabase.from('conversations').select('id,creator_id,project_id,updated_at').eq('client_id', profile.id).order('updated_at', { ascending: false }); if (queryError) { setError('Conversations could not be loaded.'); setLoading(false); return } let rows = (data ?? []) as Array<{ id: string; creator_id: string; project_id: string | null; updated_at: string }>; if (requestedCreator && !rows.some(row => row.creator_id === requestedCreator)) { const { data: created, error: createError } = await supabase.from('conversations').insert({ client_id: profile.id, creator_id: requestedCreator, project_id: requestedProject }).select('id,creator_id,project_id,updated_at').single(); if (!createError && created) rows = [created as typeof rows[number], ...rows]; else if (createError) setError('Conversation could not be opened.') } const ids = rows.map(row => row.creator_id); const creatorResult = ids.length ? await supabase.from('profiles').select('id,name,avatar_url').in('id', ids) : { data: [] as Array<{ id: string; name: string | null; avatar_url: string | null }> }; const creatorRows = (creatorResult.data ?? []) as Array<{ id: string; name: string | null; avatar_url: string | null }>; const creators = new Map(creatorRows.map((row: { id: string; name: string | null; avatar_url: string | null }) => [row.id, row])); const enriched = rows.map(row => ({ ...row, creatorName: creators.get(row.creator_id)?.name ?? 'Creator', avatar: creators.get(row.creator_id)?.avatar_url ?? null })) as Conversation[]; setConversations(enriched); setActive(params.get('conversation') ?? enriched.find(row => requestedProject ? row.project_id === requestedProject || row.creator_id === requestedCreator : row.creator_id === requestedCreator)?.id ?? enriched[0]?.id ?? ''); setLoading(false) }; void load() }, [authLoading, initialCreatorId, params, profile])
  useEffect(() => { if (!active || !profile) { setMessages([]); return } const supabase = createClient(); const markRead = async () => { await supabase.from('messages').update({ read_at: new Date().toISOString() }).eq('conversation_id', active).neq('sender_id', profile.id).is('read_at', null) }; const load = async () => { const { data, error: queryError } = await supabase.from('messages').select('id,sender_id,body,created_at,read_at').eq('conversation_id', active).order('created_at', { ascending: true }); if (queryError) setError('Messages could not be loaded.'); else { setMessages((data ?? []) as Message[]); await markRead() } }; void load(); const channel = supabase.channel(`client-messages-${active}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `conversation_id=eq.${active}` }, (payload: { new: Message }) => { const message = payload.new; setMessages(current => current.some(item => item.id === message.id) ? current : [...current, message]); if (message.sender_id !== profile.id) void supabase.from('messages').update({ read_at: new Date().toISOString() }).eq('id', message.id).eq('conversation_id', active).is('read_at', null) }).on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'messages', filter: `conversation_id=eq.${active}` }, (payload: { new: Message }) => { const message = payload.new; setMessages(current => current.map(item => item.id === message.id ? { ...item, read_at: message.read_at } : item)) }).subscribe(); return () => { void supabase.removeChannel(channel) } }, [active, profile])
  const current = conversations.find(conversation => conversation.id === active)
  const send = async () => { if (!text.trim() || !active || !profile) return; const body = text.trim(); setText(''); const { data, error: sendError } = await createClient().from('messages').insert({ conversation_id: active, sender_id: profile.id, body }).select('id,sender_id,body,created_at,read_at').single(); if (sendError) { setText(body); setError('Message could not be sent.'); return } setMessages(currentMessages => [...currentMessages, data as Message]) }
  return <Layout title="Chat"><div className="grid gap-5 lg:grid-cols-[300px_1fr]"><aside className={`${card} p-3`}><h2 className="px-3 py-2 text-sm font-semibold">Conversations</h2>{loading ? <div className="space-y-2 p-2"><div className="h-14 animate-pulse rounded-xl bg-[#3A101C]" /><div className="h-14 animate-pulse rounded-xl bg-[#3A101C]" /></div> : conversations.length ? <div className="mt-2 space-y-1">{conversations.map(conversation => <button key={conversation.id} onClick={() => setActive(conversation.id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left ${active === conversation.id ? 'bg-[#3A101C]' : 'hover:bg-[#1A080E]'}`}><span className="flex size-10 items-center justify-center overflow-hidden rounded-xl bg-[#8F1D3B] text-xs font-semibold">{conversation.avatar ? <img src={conversation.avatar} alt="" className="size-full object-cover" /> : conversation.creatorName.slice(0, 2).toUpperCase()}</span><span className="truncate text-sm">{conversation.creatorName}</span></button>)}</div> : <p className="p-3 text-sm text-[#9F8189]">Message a creator from their profile to start a conversation.</p>}</aside><section className={`${card} flex min-h-[520px] flex-col`}>{error && <p role="alert" className="m-4 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p>}{current ? <><header className="border-b border-[#3A101C] p-5"><p className="font-semibold">{current.creatorName}</p><p className="mt-1 text-xs text-[#D66A84]">Creator conversation</p></header><div className="flex-1 space-y-3 overflow-y-auto p-5">{messages.length ? messages.map(message => { const outgoing = message.sender_id === profile?.id; return <div key={message.id} className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${outgoing ? 'ml-auto bg-[#A52546]' : 'bg-[#3A101C]'}`}><p>{message.body}</p><time className={`mt-1 block text-[10px] opacity-60 ${outgoing && message.read_at ? 'text-[#F08BA7]' : ''}`}>{new Date(message.created_at).toLocaleString()} {outgoing && <span aria-label={message.read_at ? 'Read' : 'Delivered'}>✓✓</span>}</time></div> }) : <p className="py-16 text-center text-sm text-[#9F8189]">No messages yet. Start the conversation.</p>}</div><div className="border-t border-[#3A101C] p-4"><div className="flex gap-2"><textarea value={text} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.nativeEvent.isComposing) { event.preventDefault(); void send() } }} placeholder="Type a message..." className="min-w-0 flex-1 rounded-xl border border-[#6A2636] bg-[#1A080E] px-4 py-3 text-sm outline-none" /><button onClick={() => void send()} className={button} aria-label="Send message"><Send className="size-4" /></button></div></div></> : <div className="flex flex-1 items-center justify-center p-6 text-sm text-[#9F8189]">Select a conversation to start messaging.</div>}</section></div></Layout>
}
