'use client'
import Link from 'next/link'
import { createContext, useContext, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import type { Session, User } from '@supabase/supabase-js'
import { Bell, Search, ArrowLeft, Star, MapPin, CheckCircle2, Clock, Send, Paperclip } from 'lucide-react'
import { Creator, Project, Service, creatorById, projects, messages } from '@/src/data/mock'
import { ClientNav as SharedClientNav } from '@/components/client-nav'

type Profile={id:string;name:string;email:string;avatar_url:string|null;role:'client'|'creator'}
type AuthState={user:User|null;session:Session|null;profile:Profile|null;loading:boolean;isAuthenticated:boolean;role:'client'|'creator'|null;updateProfile:(p:Partial<Profile>)=>void;signOut:()=>Promise<{error:Error|null}>}
const AuthContext=createContext<AuthState>({user:null,session:null,profile:null,loading:true,isAuthenticated:false,role:null,updateProfile:()=>{},signOut:async()=>({error:null})})
export function AuthProvider({children}:{children:React.ReactNode}){const [user,setUser]=useState<User|null>(null);const [session,setSession]=useState<Session|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [loading,setLoading]=useState(true);const supabase=createClient();useEffect(()=>{let live=true;const loadProfile=async(currentUser:User|null)=>{if(!currentUser){setUser(null);setSession(null);setProfile(null);setLoading(false);return}setUser(currentUser);const {data:row,error}=await supabase.from('profiles').select('id,name,email,avatar_url,role').eq('id',currentUser.id).maybeSingle();if(!live)return;if(error){console.error('Auth profile query error:',error);setProfile(null)}else if(row){setProfile(row as Profile)}else{const fallback={id:currentUser.id,name:String(currentUser.user_metadata?.name||currentUser.email?.split('@')[0]||'Member'),email:currentUser.email||'',role:currentUser.user_metadata?.role==='creator'?'creator':'client' as 'client'|'creator',avatar_url:null};const {data:created}=await supabase.from('profiles').upsert(fallback,{onConflict:'id'}).select('id,name,email,avatar_url,role').maybeSingle();setProfile((created as Profile|null)||fallback)}setLoading(false)};supabase.auth.getSession().then(({data})=>{if(live){setSession(data.session);void loadProfile(data.session?.user||null)}});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,currentSession)=>{if(!live)return;setSession(currentSession);void loadProfile(currentSession?.user||null)});return()=>{live=false;subscription.unsubscribe()}},[supabase]);const signOut=async()=>{const {error}=await supabase.auth.signOut();if(!error){setUser(null);setSession(null);setProfile(null)}return {error:error||null}};return <AuthContext.Provider value={{user,session,profile,loading,isAuthenticated:Boolean(session),role:profile?.role||null,updateProfile:p=>setProfile(v=>v?{...v,...p}:v),signOut}}>{children}</AuthContext.Provider>}
export function useAuth(){return useContext(AuthContext)}
export const shell='min-h-screen bg-[#12070B] text-[#FFF5F6]';export const card='rounded-2xl border border-[#3A101C] bg-[#250C14]';export const button='inline-flex items-center justify-center gap-2 rounded-xl bg-[#A52546] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#C34E6D]'
export function ClientNav(){const {profile,loading}=useAuth();const [open,setOpen]=useState(false);const supabase=createClient();const initials=profile?.name?.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'';return <header className="sticky top-0 z-20 border-b border-[#3A101C] bg-[#12070B]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4"><Link href="/" className="text-lg font-semibold">Skill<span className="text-[#D66A84]">Swap</span></Link><nav className="hidden items-center gap-5 text-sm text-[#C7A7B0] md:flex"><Link href="/creators">Find creators</Link><Link href="/projects">My projects</Link><Link href="/chat">Chat</Link></nav><div className="flex items-center gap-3"><Link href="/notifications" aria-label="Notifications" className="relative"><Bell className="size-5 text-[#D66A84]"/><span className="absolute -right-1 -top-1 size-2 rounded-full bg-[#D66A84]"/></Link>{loading?<span className="size-8 animate-pulse rounded-full bg-[#3A101C]"/>:profile?<div className="relative"><button onClick={()=>setOpen(!open)} className="flex items-center gap-2 rounded-xl border border-[#54202F] bg-[#250C14] px-2 py-1.5 text-sm"><span className="flex size-8 items-center justify-center overflow-hidden rounded-full bg-[#8F1D3B] text-xs font-bold">{profile.avatar_url?<img src={profile.avatar_url} alt="" className="size-full object-cover"/>:initials}</span><span className="hidden max-w-32 truncate sm:inline">{profile.name}</span></button>{open&&<div className="absolute right-0 mt-2 w-48 rounded-xl border border-[#54202F] bg-[#250C14] p-2 shadow-xl"><Link href="/profile" className="block rounded-lg px-3 py-2 text-sm hover:bg-[#3A101C]">Profile</Link><Link href="/likes" className="block rounded-lg px-3 py-2 text-sm hover:bg-[#3A101C]">Saved creators</Link><button onClick={()=>supabase.auth.signOut()} className="w-full rounded-lg px-3 py-2 text-left text-sm text-[#E7A5B5] hover:bg-[#3A101C]">Log out</button></div>}</div>:<Link href="/login" className={button}>Log in</Link>}</div></div></header>}
export function Layout({children,title,back=false}:{children:React.ReactNode;title?:string;back?:boolean}){return <main className={shell}><SharedClientNav/><div className="mx-auto max-w-7xl px-5 py-10">{back&&<Link href="/creators" className="mb-6 inline-flex items-center gap-2 text-sm text-[#D66A84]"><ArrowLeft className="size-4"/>Back</Link>}{title&&<h1 className="mb-8 text-4xl font-semibold tracking-tight">{title}</h1>}{children}</div></main>}
export function CreatorCard({creator}:{creator:Creator}){return <article className={`${card} overflow-hidden p-5 transition hover:-translate-y-1 hover:border-[#6A2636]`}><div className="flex items-start gap-4"><img src={creator.avatar} alt="" className="size-14 rounded-2xl object-cover"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1"><h2 className="truncate font-semibold">{creator.name}</h2>{creator.verified&&<CheckCircle2 className="size-4 text-[#D66A84]"/>}</div><p className="text-sm text-[#D66A84]">{creator.category}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#9F8189]"><MapPin className="size-3"/>{creator.location}</p></div></div><p className="mt-5 line-clamp-2 text-sm leading-6 text-[#C7A7B0]">{creator.bio}</p><div className="mt-4 flex flex-wrap gap-2">{creator.skills.map(s=><span key={s} className="rounded-full border border-[#6A2636] px-2.5 py-1 text-[11px] text-[#D9A4B0]">{s}</span>)}</div><div className="mt-5 flex items-center justify-between text-sm"><span className="flex items-center gap-1"><Star className="size-4 fill-[#D66A84] text-[#D66A84]"/>{creator.rating} <span className="text-[#9F8189]">({creator.reviews})</span></span><span className="text-[#C7A0AA]">from ₹{creator.price}</span></div><div className="mt-5 grid grid-cols-2 gap-2"><Link href={`/creators/${creator.id}`} className={`${button} w-full`}>View profile</Link><Link href={`/chat?creatorId=${encodeURIComponent(creator.id)}`} className="inline-flex items-center justify-center rounded-xl border border-[#6A2636] px-3 py-2 text-sm text-[#E7A5B5]">Message</Link></div></article>}
export function Status({status}:{status:Project['status']}){return <span className="rounded-full bg-[#3A101C] px-3 py-1 text-xs text-[#E7A5B5]">{status}</span>}
export function ProjectCard({project}:{project:Project}){const creator=creatorById(project.creatorId);return <article className={`${card} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-[#9F8189]">{project.id}</p><h2 className="mt-2 font-semibold">{project.title}</h2><p className="mt-1 text-sm text-[#C7A7B0]">with {creator.name}</p></div><Status status={project.status}/></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#3A101C]"><div className="h-full rounded-full bg-[#A52546]" style={{width:`${project.progress}%`}}/></div><div className="mt-3 flex justify-between text-xs text-[#9F8189]"><span>{project.progress}% complete</span><span>Due {project.deadline}</span></div><Link href={`/projects/${project.id}`} className={`${button} mt-5 w-full`}>View details</Link></article>}
export function SearchBox({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="relative"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#9F8189]"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Search creators by name, skill, or keyword" className="w-full rounded-xl border border-[#6A2636] bg-[#1A080E] py-3 pl-11 pr-4 text-sm outline-none"/></div>}
export function ChatBox({creatorId,projectId}:{creatorId?:string;projectId?:string}){const creator=creatorById(creatorId||projects.find(p=>p.id===projectId)?.creatorId||'creator-1');const [items,setItems]=useState(messages);const [text,setText]=useState('');const send=()=>{if(text.trim()){setItems([...items,{from:'client',text,time:'Now'}]);setText('')}};return <div className={`${card} flex min-h-[520px] flex-col`}><div className="flex items-center gap-3 border-b border-[#3A101C] p-5"><img src={creator.avatar} alt="" className="size-10 rounded-xl"/><div><p className="font-semibold">{creator.name}</p><p className="text-xs text-[#D66A84]">Online · {creator.category}</p></div></div><div className="flex flex-1 flex-col gap-4 p-5">{items.map((m,i)=><div key={i} className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${m.from==='client'?'self-end bg-[#A52546]':'bg-[#3A101C]'}`}><p>{m.text}</p><span className="mt-1 block text-[10px] opacity-60">{m.time}</span></div>)}</div><div className="border-t border-[#3A101C] p-4"><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&e.keyCode!==229)send()}} placeholder="Type a message..." className="min-w-0 flex-1 rounded-xl border border-[#6A2636] bg-[#1A080E] px-4 py-3 text-sm outline-none"/><button onClick={send} className={button}><Send className="size-4"/></button></div></div></div>}
export function ServiceCard({service}:{service:Service}){return <article className={`${card} p-5`}><p className="text-xs text-[#D66A84]">SERVICE</p><h3 className="mt-3 text-lg font-semibold">{service.title}</h3><p className="mt-2 text-sm text-[#C7A7B0]">{service.description}</p><div className="mt-4 flex items-center justify-between"><span className="text-xl font-semibold">₹{service.price.toLocaleString()}</span><span className="text-xs text-[#9F8189]">{service.delivery}</span></div><Link href={`/booking/${service.id}`} className={`${button} mt-5 w-full`}>Book now</Link></article>}
export function HeaderSearch(){return <SearchBox value="" onChange={()=>{}}/>}
export function CreatorMini({creator}:{creator:Creator}){return <Link href={`/creators/${creator.id}`} className="flex items-center gap-3 rounded-xl p-3 hover:bg-[#3A101C]"><img src={creator.avatar} alt="" className="size-10 rounded-xl object-cover"/><span><b className="block text-sm">{creator.name}</b><small className="text-[#D66A84]">{creator.category}</small></span></Link>}
export const icons={Bell,Star,Clock,Paperclip,Send}
