'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useRouter } from 'next/navigation'
import { Bell, CalendarDays, CheckCircle2, ChevronLeft, CircleDollarSign, Clock3, FolderKanban, LayoutDashboard, Menu, MessageCircle, Settings, Sparkles, UserRound, Users, X } from 'lucide-react'
import { useState } from 'react'

export const creatorProjects = [
  { id: 'p-101', title: 'Brand identity for Niva', client: 'Niva Skincare', budget: 42000, progress: 68, deadline: 'Sep 29', status: 'In Progress', color: '#d66a84' },
  { id: 'p-102', title: 'Launch campaign visuals', client: 'Mosaic Foods', budget: 28000, progress: 42, deadline: 'Oct 04', status: 'In Review', color: '#8d82e8' },
  { id: 'p-103', title: 'Mobile app illustrations', client: 'Aarav Mehta', budget: 18000, progress: 18, deadline: 'Oct 11', status: 'Not Started', color: '#70c7b4' },
]

const requests = [
  { id: 'r1', client: 'Rhea Kapoor', initials: 'RK', title: 'Social launch kit for a new café', description: 'Need a warm, playful visual system for our opening campaign across Instagram and print.', budget: 24000, deadline: 'Oct 08', skills: ['Branding', 'Social media'] },
  { id: 'r2', client: 'Dev Malhotra', initials: 'DM', title: 'Landing page for a fintech product', description: 'A crisp conversion-focused landing page with a confident, editorial visual direction.', budget: 36000, deadline: 'Oct 14', skills: ['UI/UX', 'Web design'] },
  { id: 'r3', client: 'Studio North', initials: 'SN', title: 'Packaging refresh', description: 'Refresh three product labels while keeping the existing brand equity intact.', budget: 18000, deadline: 'Oct 21', skills: ['Packaging', 'Art direction'] },
]

const nav = [
  ['Home', '/creator-app/dashboard', LayoutDashboard], ['Requests', '/creator-app/requests', Users], ['Projects', '/creator-app/projects', FolderKanban], ['Messages', '/creator-app/messages', MessageCircle], ['Completed', '/creator-app/completed', CheckCircle2], ['Earnings', '/creator-app/earnings', CircleDollarSign], ['Calendar', '/creator-app/calendar', CalendarDays], ['Profile', '/creator-app/profile', UserRound], ['Settings', '/creator-app/settings', Settings],
] as const

export function CreatorShell({ children, title, eyebrow }: { children: React.ReactNode; title?: string; eyebrow?: string }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-[#0b0b12] text-[#f7f3f8]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-white/8 bg-[#101019] p-5 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between"><Link href="/creator-app/dashboard" className="flex items-center gap-2 text-xl font-bold tracking-tight"><span className="flex size-9 items-center justify-center rounded-xl bg-gradient-to-br from-[#9d71ff] to-[#61d9e6]"><Sparkles className="size-4 text-white" /></span>Skill<span className="text-[#b995ff]">Swap</span></Link><button className="lg:hidden" onClick={() => setOpen(false)} aria-label="Close menu"><X className="size-5" /></button></div>
      <div className="mt-10 rounded-2xl border border-white/8 bg-white/4 p-4"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-full bg-gradient-to-br from-[#b995ff] to-[#61d9e6] font-bold text-[#161120]">AS</div><div><p className="text-sm font-semibold">Aisha Sharma</p><p className="text-xs text-white/45">Product designer</p></div></div><div className="mt-4 flex items-center gap-2 text-xs text-[#7ce0c1]"><span className="size-2 rounded-full bg-[#7ce0c1]" />Available for work</div></div>
      <nav className="mt-8 flex flex-1 flex-col gap-1">{nav.map(([label, href, Icon]) => { const active = pathname === href || (label === 'Projects' && pathname.startsWith('/creator-app/projects/')); return <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${active ? 'bg-gradient-to-r from-[#6f4fc0]/35 to-transparent text-white' : 'text-white/50 hover:bg-white/5 hover:text-white'}`}><Icon className="size-4" />{label}{label === 'Requests' && <span className="ml-auto rounded-full bg-[#c779a0]/20 px-2 py-0.5 text-[10px] text-[#f2aac6]">3</span>}</Link> })}</nav>
      <div className="border-t border-white/8 pt-4 text-xs text-white/35">Creator workspace · v1.0</div>
    </aside>
    {open && <button className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation" />}
    <main className="lg:pl-72"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-white/8 bg-[#0b0b12]/85 px-5 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><button className="rounded-xl border border-white/10 p-2 lg:hidden" onClick={() => setOpen(true)} aria-label="Open menu"><Menu className="size-5" /></button><div><p className="hidden text-xs uppercase tracking-[0.24em] text-[#b995ff] sm:block">{eyebrow || 'Creator workspace'}</p><h1 className="text-lg font-semibold sm:text-xl">{title || 'Good morning, Aisha'}</h1></div></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-xl border border-white/8 bg-white/4 px-3 py-2 text-xs text-white/45 md:flex"><span className="size-2 rounded-full bg-[#7ce0c1]" />Available</div><Link href="/creator-app/notifications" className="relative rounded-xl border border-white/10 p-2.5 text-white/65 hover:text-white"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#f2aac6]" /></Link><div className="flex size-9 items-center justify-center rounded-full bg-gradient-to-br from-[#b995ff] to-[#61d9e6] text-xs font-bold text-[#161120]">AS</div></div></header><div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8">{children}</div></main>
  </div>
}

export function StatCard({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: typeof Clock3 }) { return <div className="rounded-2xl border border-white/8 bg-white/[0.045] p-5"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.16em] text-white/40">{label}</p><Icon className="size-4 text-[#b995ff]" /></div><p className="mt-4 font-mono text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#7ce0c1]">{note}</p></div> }
export function Pill({ children, tone = 'purple' }: { children: React.ReactNode; tone?: 'purple' | 'green' | 'amber' | 'pink' }) { const colors = { purple: 'bg-[#b995ff]/12 text-[#d3c2ff]', green: 'bg-[#7ce0c1]/12 text-[#9debd1]', amber: 'bg-[#f2c879]/12 text-[#f6d99e]', pink: 'bg-[#f2aac6]/12 text-[#f2aac6]' }; return <span className={`rounded-full px-2.5 py-1 text-[11px] ${colors[tone]}`}>{children}</span> }
export { requests }
export function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold">{title}</h2>{action}</div> }
export function ProjectRow({ project }: { project: typeof creatorProjects[number] }) { return <Link href={`/creator-app/projects/${project.id}`} className="block rounded-2xl border border-white/8 bg-white/[0.045] p-5 transition hover:-translate-y-0.5 hover:border-[#b995ff]/35"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-white/40">{project.client}</p><h3 className="mt-1 font-semibold">{project.title}</h3></div><Pill tone={project.status === 'In Review' ? 'purple' : 'green'}>{project.status}</Pill></div><div className="mt-5 flex items-center justify-between text-xs text-white/45"><span>{project.progress}% complete</span><span className="flex items-center gap-1"><Clock3 className="size-3" />Due {project.deadline}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-[#9d71ff] to-[#61d9e6]" style={{ width: `${project.progress}%` }} /></div></Link> }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-white/12 bg-white/[0.02] p-12 text-center"><Sparkles className="mx-auto size-7 text-[#b995ff]" /><h3 className="mt-4 font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-white/45">{description}</p></div> }
export function ContactPanel() { return <div className="rounded-2xl border border-white/8 bg-white/[0.045] p-5"><p className="text-xs uppercase tracking-[0.16em] text-white/40">Client contact</p><div className="mt-4 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-full bg-[#f2aac6]/20 text-sm font-semibold text-[#f2aac6]">NK</div><div><p className="font-semibold">Niva Kapoor</p><p className="text-xs text-white/45">niva@niva.co</p></div></div><div className="mt-5 space-y-3 text-sm text-white/55"><p>New Delhi · IST</p><p>Member since 2023 · 4 projects together</p></div><Link href="/creator-app/messages" className="mt-5 block rounded-xl border border-white/10 px-4 py-3 text-center text-sm font-medium hover:bg-white/5">Message client</Link></div> }
function CreatorLogout() { const router = useRouter(); const [error, setError] = useState(''); const logout = async () => { setError(''); const { error: signOutError } = await import('@/lib/supabase/client').then(({ createClient }) => createClient().auth.signOut()); if (signOutError) { setError('Unable to log out. Please try again.'); return } router.replace('/'); router.refresh() }; return <div className="mb-5 border-b border-white/8 pb-5"><button onClick={logout} className="w-full rounded-xl border border-white/10 px-3 py-2 text-left text-sm text-white/65 hover:bg-white/5 hover:text-white">Log out</button>{error && <p role="alert" className="mt-2 text-xs text-[#f2aac6]">{error}</p>}</div> }
export function CreatorPage({ children, title, eyebrow }: { children: React.ReactNode; title?: string; eyebrow?: string }) { return <CreatorShell title={title} eyebrow={eyebrow}><CreatorLogout />{children}</CreatorShell> }
export function SectionGrid({ children }: { children: React.ReactNode }) { return <div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]">{children}</div> }
export function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm"><span className="text-white/50">{label}</span>{children}</label> }
export const inputClass = 'rounded-xl border border-white/10 bg-white/[0.04] px-3.5 py-3 text-sm text-white outline-none transition placeholder:text-white/25 focus:border-[#b995ff]/70'
export const primaryButton = 'inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#9d71ff] to-[#61d9e6] px-4 py-2.5 text-sm font-semibold text-[#11101a] transition hover:brightness-110'
export const secondaryButton = 'inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-medium text-white transition hover:bg-white/10'
export const mono = 'font-mono'
export const muted = 'text-white/45'
export const cardClass = 'rounded-2xl border border-white/8 bg-white/[0.045]'
export const gradientText = 'bg-gradient-to-r from-[#d6c5ff] to-[#74e5ee] bg-clip-text text-transparent'
export const backLink = <Link href="/creator-app/dashboard" className="inline-flex items-center gap-2 text-sm text-white/45 hover:text-white"><ChevronLeft className="size-4" />Back to dashboard</Link>
