'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Search } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { card, button } from '@/components/client-shell'

type Gig = { id: string; creator_name: string; creator_username: string; title: string; category: string; rate: number; description: string; created_at: string }

export default function MarketplacePage() {
  const [gigs, setGigs] = useState<Gig[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { createClient().from('demo_gigs').select('*').order('created_at', { ascending: false }).then(({ data, error: queryError }) => { if (queryError) setError('Marketplace could not be loaded. Apply the demo migration, then retry.'); else setGigs((data ?? []) as Gig[]); setLoading(false) }) }, [])
  const categories = ['All', ...new Set(gigs.map(gig => gig.category))]
  const filtered = useMemo(() => gigs.filter(gig => (category === 'All' || gig.category === category) && `${gig.title} ${gig.creator_name} ${gig.category} ${gig.description}`.toLowerCase().includes(query.toLowerCase())), [category, gigs, query])
  return <main className="min-h-screen bg-[#12070B] px-5 py-10 text-[#FFF5F6]"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#D66A84]">PUBLIC DEMO MARKETPLACE</p><h1 className="mt-3 text-4xl font-semibold">Browse creator gigs.</h1><p className="mt-3 text-[#C7A7B0]">Explore, search, and book without creating an account.</p></div><Link href="/bookings" className="text-sm text-[#D66A84]">My bookings</Link></div><div className="mt-8 grid gap-3 md:grid-cols-[1fr_auto]"><div className="relative"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#9F8189]" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search gigs, creators, or categories" className="w-full rounded-xl border border-[#6A2636] bg-[#1A080E] py-3 pl-11 pr-4 text-sm outline-none" /></div><select value={category} onChange={event => setCategory(event.target.value)} className="rounded-xl border border-[#6A2636] bg-[#1A080E] px-4 py-3 text-sm">{categories.map(value => <option key={value}>{value}</option>)}</select></div>{error && <p role="alert" className="mt-5 rounded-xl border border-rose-300/30 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</p>}{loading ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(item => <div key={item} className={`${card} h-64 animate-pulse`} />)}</div> : filtered.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{filtered.map(gig => <article className={`${card} flex flex-col`} key={gig.id}><p className="text-xs text-[#D66A84]">{gig.category}</p><h2 className="mt-3 text-lg font-semibold">{gig.title}</h2><p className="mt-2 text-sm text-[#C7A7B0]">{gig.description}</p><p className="mt-4 text-sm text-[#9F8189]">{gig.creator_name} · {gig.creator_username}</p><div className="mt-auto flex items-center justify-between border-t border-[#3A101C] pt-5"><span className="font-semibold">₹{Number(gig.rate).toLocaleString('en-IN')}</span><Link href={`/gigs/${gig.id}`} className={button}>View gig</Link></div></article>)}</div> : <div className={`${card} mt-8 p-12 text-center text-sm text-[#9F8189]`}>No gigs match your search.</div>}</div></main>
}
