'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { card, button } from '@/components/client-shell'

type Booking = { id: string; gig_id: string; client_name: string; requirements: string; status: string; created_at: string; demo_gigs: { title: string; creator_name: string } | null }

export default function CreatorDemoPage() {
  const [bookings, setBookings] = useState<Booking[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState('')
  const load = async () => { const { data, error: queryError } = await createClient().from('demo_bookings').select('id,gig_id,client_name,requirements,status,created_at,demo_gigs(title,creator_name)').order('created_at', { ascending: false }); if (queryError) setError('Incoming bookings could not be loaded.'); else setBookings((data ?? []) as unknown as Booking[]); setLoading(false) }
  useEffect(() => { void load() }, [])
  const decide = async (booking: Booking, status: 'accepted' | 'declined') => { setBusy(booking.id); setError(''); if (status === 'accepted') { const { data: conflict } = await createClient().from('demo_bookings').select('id').eq('gig_id', booking.gig_id).eq('status', 'accepted').neq('id', booking.id).maybeSingle(); if (conflict) { setError('This gig already has an accepted booking.'); setBusy(''); return } } const { error: updateError } = await createClient().from('demo_bookings').update({ status, updated_at: new Date().toISOString() }).eq('id', booking.id).eq('status', 'pending'); if (updateError) setError('Booking status could not be updated.'); else await load(); setBusy('') }
  return <main className="min-h-screen bg-[#12070B] px-5 py-10 text-[#FFF5F6]"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-[#D66A84]">PUBLIC DEMO</p><h1 className="mt-3 text-4xl font-semibold">Creator dashboard</h1></div><Link href="/marketplace" className="text-sm text-[#D66A84]">Back to marketplace</Link></div>{error && <p role="alert" className="mt-5 rounded-xl bg-rose-500/10 p-4 text-sm text-rose-200">{error}</p>}{loading ? <div className={`${card} mt-8 h-48 animate-pulse`} /> : bookings.length ? <div className="mt-8 grid gap-4">{bookings.map(booking => <article className={`${card} flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between`} key={booking.id}><div><p className="text-xs text-[#9F8189]">{new Date(booking.created_at).toLocaleDateString()}</p><h2 className="mt-2 text-lg font-semibold">{booking.demo_gigs?.title || 'Gig'} · {booking.client_name}</h2><p className="mt-2 text-sm text-[#C7A7B0]">{booking.requirements}</p><span className="mt-3 inline-block rounded-full bg-[#3A101C] px-3 py-1 text-xs text-[#E7A5B5]">{booking.status}</span></div>{booking.status === 'pending' && <div className="flex gap-2"><button disabled={busy === booking.id} onClick={() => void decide(booking, 'accepted')} className={`${button} disabled:opacity-50`}>Accept</button><button disabled={busy === booking.id} onClick={() => void decide(booking, 'declined')} className="rounded-xl border border-[#6A2636] px-4 py-2.5 text-sm disabled:opacity-50">Decline</button></div>}</article>)}</div> : <div className={`${card} mt-8 p-12 text-center text-sm text-[#9F8189]`}>No incoming bookings yet.</div>}</div></main>
}
